Test

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -13,31 +13,6 @@ jobs:
         steps:
         -   name: Checkout the code
             uses: actions/checkout@v4
-            
-        -   name: Setup JAVA 17
-            uses: actions/setup-java@v3
-            with:
-                distribution: 'corretto'
-                java-version: 17
-
-        -   name: Run lint
-            run: ./gradlew lint
-
-        -   name: Run Unit Test
-            run: ./gradlew test
-
-        -   name: Unit tests results
-            uses: actions/upload-artifact@v3
-            with:
-              name: unit-tests-results
-              path: app/build/reports/tests/testDebugUnitTest/index.html
-    lint:
-        name: Lint Check
-        runs-on: ubuntu-latest
-        
-        steps:
-        -   name: Checkout the code
-            uses: actions/checkout@v4
                 
         -   name: Setup JAVA 17
             uses: actions/setup-java@v3
@@ -46,6 +21,9 @@ jobs:
                 java-version: 17
                 cache: 'gradle'
     
+        -   name: Grant execute permission for gradlew
+            run: chmod +x gradlew
+
         # -   name: Run lint
         #     run: ./gradlew lint
     
@@ -55,8 +33,8 @@ jobs:
         -   name: Archive test report
             uses: actions/upload-artifact@v3
             with:
-              name: Test report
-              path: build/reports/tests/test
+                name: Test report
+                path: build/reports/tests/test
 
         # -   name: Unit tests results
         #     uses: actions/upload-artifact@v3
@@ -64,3 +42,36 @@ jobs:
         #     with:
         #         name: test-results
         #         path: jest-junit.xml
+    # lint:
+    #     name: Lint Check
+    #     runs-on: ubuntu-latest
+        
+    #     steps:
+    #     -   name: Checkout the code
+    #         uses: actions/checkout@v4
+                
+    #     -   name: Setup JAVA 17
+    #         uses: actions/setup-java@v3
+    #         with:
+    #             distribution: 'corretto'
+    #             java-version: 17
+    #             cache: 'gradle'
+    
+    #     # -   name: Run lint
+    #     #     run: ./gradlew lint
+    
+    #     -   name: Run Unit Test
+    #         run: ./gradlew test
+    
+    #     -   name: Archive test report
+    #         uses: actions/upload-artifact@v3
+    #         with:
+    #           name: Test report
+    #           path: build/reports/tests/test
+
+    #     # -   name: Unit tests results
+    #     #     uses: actions/upload-artifact@v3
+    #     #     if: success() || failure()        # run this step even if previous step failed
+    #     #     with:
+    #     #         name: test-results
+    #     #         path: jest-junit.xml
